command: tor

user: debian-tor
group: debian-tor

config_files:
    - /etc/tor/torrc

post_conf_commands:
    - timeout 3s tor > /dev/null || true
    - onions
    - chown -R debian-tor:debian-tor $HOME

debug: false
